{
    "openapi": "3.0.1",
    "info": {
        "title": "Renpass.UOL",
        "description": "API for renting luxury and semi-luxury cars",
        "contact": {
            "email": "graciparentte@gmail.com",
            "url": "https://github.com/gracicomc/"
        },
        "version": "0.0.1"
    },
    "servers": [
        {
            "url": "https://renpassuol.herokuapp.com/api/v1",
            "description": "API server"
        }
    ],
    "paths": {
        "/authenticate/": {
            "post": {
                "summary": "Authenticate user",
                "description": "Authenticate user",
                "tags": ["Authentication"],
                "requestBody": { 
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/PersonSchema"
                            },
                            "examples": {
                                "person": {
                                    "value": {
                                        "email": "joao@email.com",
                                        "password": "123456"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "400": {
                        "description": "Bad request"
                    },
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/PersonSchema"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/car/": {
            "post": {
                "summary": "Create a car",
                "description": "Create a car",
                "tags": ["Cars"],
                "security": [{"bearerAuth": []}],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref":"#/components/schemas/CarSchema"
                            },
                            "examples": {
                                "car": {
                                    "value": {
                                        
                                        "model": "S10 3.0",
                                        "type": "sedan",
                                        "brand": "GM",
                                        "color": "azul",
                                        "year": "2022",
                                        "accessories": [
                                            {
                                                "description": "Ar-condicionado"
                                            },
                                            {
                                                "description": "Dir. Hidr치ulica"
                                            },
                                            {
                                                "description": "C칙mbio Autom치tico"
                                            },
                                            {
                                                "description": "Teto Solar"
                                            }
                                            ],
                                        "passengersQtd": 5            
                                    }
                                }
                            }
                        }
                    }                  
                },
                "responses": {
                    "400": {
                        "description": "Bad request"
                    },
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/CarSchema"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "List all cars",
                "description": "List all cars",
                "tags": ["Cars"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name": "model",
                        "in": "query",
                        "description": "Search by model",
                        "schema": {
                            "type": "string"
                        } 
                    },
                    {
                        "name": "type",
                        "in": "query",
                        "description": "Search by type",
                        "schema": {
                            "type": "string"
                        }       
                    },
                    {
                        "name": "brand",
                        "in": "query",
                        "description": "Search by brand",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "color",
                        "in": "query",
                        "description": "Search by color",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "year",
                        "in": "query",
                        "description": "Search by year",
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "activities",
                        "in": "query",
                        "description": "Search by activities",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/CarSchema"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/car/{id}": {
            "get": {
                "summary": "Get a car by id",
                "description": "Get a car by id",
                "tags": ["Cars"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Car id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/CarSchema"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found"
                    }
                }
            },
            "patch": {
                "summary": "Update a car by id",
                "description": "Update a car by id",
                "tags": ["Cars"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Car id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref":"#/components/schemas/CarSchema"
                            },
                            "examples": {
                                "car": {
                                    "value": {
                                        
                                        "model": "S10 3.0",
                                        "type": "sedan",
                                        "brand": "GM",
                                        "color": "vermelho",
                                        "year": "2020",
                                        "accessories": [
                                            {
                                                "description": "Quatro Portas"
                                            },
                                            {
                                                "description": "Dir. Hidr치ulica"
                                            },
                                            {
                                                "description": "C칙mbio Manual"
                                            }
                                            ],
                                        "passengersQtd": 4            
                                    }
                                }
                            }
                        }
                    }                  
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/CarSchema"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found"
                    }
                }
            },
            "delete": {
                "summary": "Delete a car by id",
                "description": "Delete a car by id",
                "tags": ["Cars"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Car id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No content"
                    },
                    "404": {
                        "description": "Not found"
                    }
                }
            }
        },
        "/car/{id}/accessories/{accessoriesId}": {
            "patch": {
                "summary": "Update an accessory by id",
                "description": "Update an accessory by id",
                "tags": ["Cars"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Car id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "accessoriesId",
                        "in": "path",
                        "description": "ccessory id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref":"#/components/schemas/CarSchema"
                            },
                            "examples": {
                                "car": {
                                    "value": {
                                        "description": "Quatro Portas"
                                    }
                                }
                            }
                        }
                    }                  
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/CarSchema"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found"
                    }
                }
            }
        },
        "/person/": {
            "post": {
                "summary": "Create a person",
                "description": "Create a person",
                "tags": ["Person"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref":"#/components/schemas/PersonSchema"
                            },
                            "examples": {
                                "person": {
                                    "value": {
                                        "name": "Jo칚o",
                                        "cpf": "504.527.140-79",
                                        "birthDay": "20/08/1998",
                                        "email": "joao@email.com",
                                        "password": "123456",
                                        "canDrive": "yes"    
                                    }
                                }
                            }
                        }
                    }                  
                },
                "responses": {
                    "400": {
                        "description": "Bad request"
                    },
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/PersonSchema"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "List all people",
                "description": "List all people",
                "tags": ["Person"],
                "parameters": [
                    {
                        "name": "name",
                        "in": "query",
                        "description": "Search by name",
                        "schema": {
                            "type": "string"
                        } 
                    },
                    {
                        "name": "cpf",
                        "in": "query",
                        "description": "Search by cpf",
                        "schema": {
                            "type": "string"
                        }       
                    },
                    {
                        "name": "birthDay",
                        "in": "query",
                        "description": "Search by birthDay",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "email",
                        "in": "query",
                        "description": "Search by email",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "password",
                        "in": "query",
                        "description": "Search by password",
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "activities",
                        "in": "query",
                        "description": "Search by activities",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/PersonSchema"
                                    }
                                }
                            }
                        }
                    }
                }
            }   
        },
        "/person/{id}": {
            "get": {
                "summary": "Get a person by id",
                "description": "Get a person by id",
                "tags": ["Person"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Person id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/PersonSchema"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found"
                    }
                }
            },
            "patch": {
                "summary": "Update a person by id",
                "description": "Update a person by id",
                "tags": ["Person"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Person id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref":"#/components/schemas/PersonSchema"
                            },
                            "examples": {
                                "car": {
                                    "value": {
                                        "name": "Jo칚o Gomes",
                                        "cpf": "504.527.140-79",
                                        "birthDay": "20/08/1998",
                                        "email": "joao.gomes@email.com",
                                        "password": "654321",
                                        "canDrive": "yes"    
                                    }
                                }
                            }
                        }
                    }                  
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/PersonSchema"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found"
                    }
                }
            },
            "delete": {
                "summary": "Delete a person by id",
                "description": "Delete a person by id",
                "tags": ["Person"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Person id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No content"
                    },
                    "404": {
                        "description": "Not found"
                    }
                }
            }
        },
        "/rental/": {
            "post": {
                "summary": "Create a rental",
                "description": "Create a rental",
                "tags": ["Rental"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref":"#/components/schemas/RentalSchema"
                            },
                            "examples": {
                                "car": {
                                    "value": {  
                                            "name": "Localiza Rent a Car",
                                            "cnpj": "08.366.064/0001-12",
                                            "activities": "Aluguel de Carros E Gest칚o de Frotas",
                                            "address": [
                                                {
                                                    "zipCode": "68459-020",
                                                    "number": "200",
                                                    "isFilial": true
                                                }
                                            ]  
                                    }
                                }
                            }
                        }
                    }                  
                },
                "responses": {
                    "400": {
                        "description": "Bad request"
                    },
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/RentalSchema"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "List all Rentals",
                "description": "List all Rentals",
                "tags": ["Rental"],
                "parameters": [
                    {
                        "name": "name",
                        "in": "query",
                        "description": "Search by name",
                        "schema": {
                            "type": "string"
                        } 
                    },
                    {
                        "name": "cnpj",
                        "in": "query",
                        "description": "Search by cnpj",
                        "schema": {
                            "type": "string"
                        }       
                    },
                    {
                        "name": "address",
                        "in": "query",
                        "description": "Search by address",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "activities",
                        "in": "query",
                        "description": "Search by activities",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/RentalSchema"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/rental/{id}": {
            "get": {
                "summary": "Get a Rental by id",
                "description": "Get a Rental by id",
                "tags": ["Rental"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Rental id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/RentalSchema"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found"
                    }
                }
            },
            "patch": {
                "summary": "Update a Rental by id",
                "description": "Update a Rental by id",
                "tags": ["Rental"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Rental id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref":"#/components/schemas/RentalSchema"
                            },
                            "examples": {
                                "car": {
                                    "value": {
                                        "name": "Localiza",
                                        "cnpj": "08.366.064/0001-12",
                                        "activities": "Aluguel de Carros E Gest칚o de Frotas",
                                        "address": [
                                            {
                                                "zipCode": "68459-020",
                                                "number": "230",
                                                "isFilial": true
                                            }
                                        ]            
                                    }
                                }
                            }
                        }
                    }                  
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/RentalSchema"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found"
                    }
                }
            },
            "delete": {
                "summary": "Delete a Rental by id",
                "description": "Delete a Rental by id",
                "tags": ["Rental"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Rental id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No content"
                    },
                    "404": {
                        "description": "Not found"
                    }
                }
            }
        },
        "/rental/{rentalId}/fleet/": {
            "post": {
                "summary": "Create a fleet",
                "description": "Create a fleet",
                "tags": ["Fleets"],
                "parameters": [
                    {
                        "name": "rentalId",
                        "in": "path",
                        "description": "Rental Id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref":"#/components/schemas/FleetSchema"
                            },
                            "examples": {
                                "fleet": {
                                    "value": {
                                        "id_car": "62b0ba0be023cf8d212ad608",
                                        "status": "available",
                                        "daily_value": 100,
                                        "plate": "MVJ8786"
                                    }
                                }
                            }
                        }
                    }                  
                },
                "responses": {
                    "400": {
                        "description": "Bad request"
                    },
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/FleetSchema"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "List all fleets",
                "description": "List all fleets",
                "tags": ["Fleets"],
                "parameters": [
                    {
                        "name": "rentalId",
                        "in": "path",
                        "description": "Rental Id",
                        "required": true,
                        "schema": {
                            "type": "string"
                    }
                    },
                    {
                        "name": "id_car",
                        "in": "query",
                        "description": "Search by Car ID",
                        "schema": {
                            "type": "string"
                        } 
                    },
                    {
                        "name": "id_rental",
                        "in": "query",
                        "description": "Search by Rental ID",
                        "schema": {
                            "type": "string"
                        }       
                    },
                    {
                        "name": "status",
                        "in": "query",
                        "description": "Search by Status",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "daily_value",
                        "in": "query",
                        "description": "Search by Daily Value",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "plate",
                        "in": "query",
                        "description": "Search by Plate",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "_id",
                        "in": "query",
                        "description": "Search by Fleets ID",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/FleetSchema"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/rental/{rentalId}/fleet/{id}": {
            "get": {
                "summary": "Get a fleet by ID",
                "description": "Get a fleet by ID",
                "tags": ["Fleets"],
                "parameters": [
                    {
                        "name": "rentalId",
                        "in": "path",
                        "description": "Rental Id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Fleet ID",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/FleetSchema"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found"
                    }
                }
            },
            "patch": {
                "summary": "Update a fleet by ID",
                "description": "Update a fleet by ID",
                "tags": ["Fleets"],
                "parameters": [
                    {
                        "name": "rentalId",
                        "in": "path",
                        "description": "Rental Id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Fleet ID",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref":"#/components/schemas/FleetSchema"
                            },
                            "examples": {
                                "fleet": {
                                    "value": {
                                        "id_car": "62b0ba0be023cf8d212ad608",
                                        "status": "unavailable",
                                        "daily_value": 100,
                                        "plate": "MVJ8786"
                                    }
                                }
                            }
                        }
                    }                  
                },
                "responses": {
                    "400": {
                        "description": "Bad request"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/FleetSchema"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Delete a fleet by ID",
                "description": "Delete a fleet by ID",
                "tags": ["Fleets"],
                "parameters": [
                    {
                        "name": "rentalId",
                        "in": "path",
                        "description": "Rental Id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Fleet ID",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/FleetSchema"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found"
                    }
                }
            }
        },
        "/rental/{rentalId}/reserve/": {
            "post": {
                "summary": "Create a Reserve",
                "description": "Create a Reserve",
                "tags": ["Reserves"],
                "parameters": [
                    {
                        "name": "rentalId",
                        "in": "path",
                        "description": "Rental Id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref":"#/components/schemas/ReserveSchema"
                            },
                            "examples": {
                                "reserve": {
                                    "value": {
                                        "id_user": "62b1d6e27b943caf405128d1",
                                        "date_start": "10/01/2022",
                                        "date_end": "12/01/2022",
                                        "id_car": "62b0ba0be023cf8d212ad608"
                                    }
                                }
                            }
                        }
                    }                  
                },
                "responses": {
                    "400": {
                        "description": "Bad request"
                    },
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/ReserveSchema"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "List all Reserves",
                "description": "List all Reserves",
                "tags": ["Reserves"],
                "parameters": [
                    {
                        "name": "rentalId",
                        "in": "path",
                        "description": "Rental Id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "id_user",
                        "in": "query",
                        "description": "Search by User ID",
                        "schema": {
                            "type": "string"
                        } 
                    },
                    {
                        "name": "date_start",
                        "in": "query",
                        "description": "Search by Start Date",
                        "schema": {
                            "type": "string"
                        }       
                    },
                    {
                        "name": "date_end",
                        "in": "query",
                        "description": "Search by End Date",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "id_car",
                        "in": "query",
                        "description": "Search by Car ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "_id",
                        "in": "query",
                        "description": "Search by Reserves ID",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/ReserveSchema"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/rental/{rentalId}/reserve/{id}": {
            "get": {
                "summary": "Get a Reserve by ID",
                "description": "Get a Reserve by ID",
                "tags": ["Reserves"],
                "parameters": [
                    {
                        "name": "rentalId",
                        "in": "path",
                        "description": "Rental Id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Reserve ID",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ReserveSchema"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found"
                    }
                }
            },
            "patch": {
                "summary": "Update a Reserve by ID",
                "description": "Update a Reserve by ID",
                "tags": ["Reserves"],
                "parameters": [
                    {
                        "name": "rentalId",
                        "in": "path",
                        "description": "Rental Id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Reserve ID",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref":"#/components/schemas/ReserveSchema"
                            },
                            "examples": {
                                "reserve": {
                                    "value": {
                                        "id_user": "62b1d6e27b943caf405128d1",
                                        "date_start": "20/01/2022",
                                        "date_end": "22/01/2022",
                                        "id_car": "62b0ba0be023cf8d212ad608"
                                    }
                                }
                            }
                        }
                    }                  
                },
                "responses": {
                    "400": {
                        "description": "Bad request"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/ReserveSchema"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Delete a Reserve by ID",
                "description": "Delete a Reserve by ID",
                "tags": ["Reserves"],
                "parameters": [
                    {
                        "name": "rentalId",
                        "in": "path",
                        "description": "Rental Id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Reserve ID",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ReserveSchema"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found"
                    }
                }
            }

        }
    },
    "components": {
        "schemas": {
            "CarSchema": {
                "type": "object",
                "properties": {
                    "model": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    },
                    "color": {
                        "type": "string"
                    },
                    "year": {
                        "type": "number"
                    },
                    "accessories": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "description": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "passengersQtd": {
                        "type": "number"
                    },
                    "_id": {
                        "type": "string"
                    }
                }
            },
            "PersonSchema":{
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "cpf": {
                        "type": "string"

                    },
                   "birthDay": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    },
                    "canDrive": {
                        "type": "string"
                    },
                    "_id": {
                        "type": "string"
                    }
                    }
            },
            "RentalSchema": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "cnpj": {
                        "type": "string"
                    },
                    "activities": {
                        "type": "string"
                    },
                    "address": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "zipCode": {
                                    "type": "string"
                                },
                                "street": {
                                    "type": "string"
                                },
                                "number": {
                                    "type": "number"
                                },
                                "city": {
                                    "type": "string"
                                },
                                "district": {
                                    "type": "string"
                                },
                                "state": {
                                    "type": "string"
                                },
                                "isFillial": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "FleetSchema": {
                "type": "object",
                "properties": {
                    "id_car": {
                        "type": "string"
                    },
                    "id_rental": {
                        "type": "string"
                    },
                    "status": {
                        "type": "string"
                    },
                    "daily_value": {
                        "type": "number"
                    },
                    "plate": {
                        "type": "string"
                    },
                    "_id": {
                        "type": "string"
                    }
                }
            },
            "ReserveSchema": {
                "type": "object",
                "properties": {
                    "id_user": {
                        "type": "string"
                    },
                    "date_start": {
                        "type": "string"
                    },
                    "date_end": {
                        "type": "string"
                    },
                    "id_car": {
                        "type": "string"
                    },
                    "id_rental": {
                        "type": "string"
                    },
                    "_id": {
                        "type": "string"
                    }
                }
            }
        },
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}
